import mongoose, { Schema } from "mongoose";

const tripPlaceSchema = new Schema(
  {
    trip: {
      type: Schema.Types.ObjectId,
      ref: "Trip",
      required: true,
      index: true,
    },

    // BASIC
    name: { type: String, required: true }, // Taj Mahal
    category: {
      type: String,
      enum: [
        "monument",
        "temple",
        "market",
        "nature",
        "museum",
        "food",
        "other",
      ],
      required: true,
    },

    // LINKS (official site, maps, tickets, insta, etc.)
    links: [
      {
        label: {
          type: String, // "Official Website", "Google Maps", "Tickets"
          required: true,
        },
        url: {
          type: String,
          required: true,
        },
        type: {
          type: String,
          enum: ["official", "maps", "tickets", "social", "other"],
          default: "other",
        },
      },
    ],

    // LOCATION (human + geo)
    location: {
      name: String, // Agra, Uttar Pradesh

      coordinates: {
        type: {
          type: String,
          enum: ["Point"],
        },
        coordinates: {
          type: [Number], // [lng, lat]
        },
      },
    },

    // IMAGE (single cover is enough for now)
    image: {
      url: String,
      source: {
        type: String,
        enum: ["agency", "ai", "external"],
        default: "agency",
      },
    },

    // SHORT HIGHLIGHTS (points of location)
    points: [String], // ["Sunrise visit", "Guided tour", "Photo spot"]

    autoGenerated: { type: Boolean, default: true },
  },
  { timestamps: true }
);

tripPlaceSchema.index({ "location.coordinates": "2dsphere" });

export const TripPlace = mongoose.model("TripPlace", tripPlaceSchema);
